"""Task 2: audit GTFS integrity and identify bidirectional corridors."""

from __future__ import annotations

import sys

import pandas as pd

from common import GTFS_FILES, PROCESSED_DIR, ensure_output_dirs, load_gtfs


def pct(numerator: int, denominator: int) -> float:
    return 100.0 if denominator == 0 else numerator / denominator * 100.0


def main() -> int:
    ensure_output_dirs()
    tables = {name: load_gtfs(name) for name in GTFS_FILES}
    routes = tables["routes.txt"]
    trips = tables["trips.txt"]
    stops = tables["stops.txt"]
    stop_times = tables["stop_times.txt"]
    frequencies = tables["frequencies.txt"]

    missing_trip_routes = sorted(set(trips["route_id"]) - set(routes["route_id"]))
    missing_stop_refs = sorted(set(stop_times["stop_id"]) - set(stops["stop_id"]))
    missing_frequency_trips = sorted(set(frequencies["trip_id"]) - set(trips["trip_id"]))

    integrity = {
        "trips.route_id -> routes.route_id": len(missing_trip_routes),
        "stop_times.stop_id -> stops.stop_id": len(missing_stop_refs),
        "frequencies.trip_id -> trips.trip_id": len(missing_frequency_trips),
    }

    corridor_groups = (
        routes.assign(route_long_name=routes["route_long_name"].fillna("").str.strip())
        .groupby(["agency_id", "route_long_name"], dropna=False)
        .agg(
            representative_route_id=("route_id", "first"),
            route_ids=("route_id", lambda values: "|".join(sorted(set(values)))),
            direction_count=("route_id", "nunique"),
            route_desc=("route_desc", "first"),
        )
        .reset_index()
    )
    corridor_groups["bidirectional_pair_flag"] = corridor_groups["direction_count"].gt(1)
    corridor_groups.to_csv(PROCESSED_DIR / "route_corridors.csv", index=False)

    report = [
        "# GTFS audit report",
        "",
        "Generated by `python src/01_audit.py`. The raw source files are never modified.",
        "",
        "## Row counts",
        "",
        "| File | Rows |",
        "|---|---:|",
    ]
    report.extend(f"| `{name}` | {len(frame):,} |" for name, frame in tables.items())
    report.extend(
        [
            "",
            "## Referential integrity",
            "",
            "| Relationship | Coverage | Missing references | Result |",
            "|---|---:|---:|---|",
            f"| trips to routes | {pct(len(trips) - trips['route_id'].isin(missing_trip_routes).sum(), len(trips)):.2f}% | {len(missing_trip_routes):,} | {'PASS' if not missing_trip_routes else 'FAIL'} |",
            f"| stop_times to stops | {pct(len(stop_times) - stop_times['stop_id'].isin(missing_stop_refs).sum(), len(stop_times)):.2f}% | {len(missing_stop_refs):,} | {'PASS' if not missing_stop_refs else 'FAIL'} |",
            f"| frequencies to trips | {pct(len(frequencies) - frequencies['trip_id'].isin(missing_frequency_trips).sum(), len(frequencies)):.2f}% | {len(missing_frequency_trips):,} | {'PASS' if not missing_frequency_trips else 'FAIL'} |",
            "",
            "## Bidirectional corridor handling",
            "",
            f"The feed contains {len(routes):,} route-direction records and {len(corridor_groups):,} unique agency/name corridor groups. "
            f"{int(corridor_groups['bidirectional_pair_flag'].sum()):,} corridor groups have multiple route IDs. "
            "`route_corridors.csv` is the de-duplicated corridor view and preserves all underlying IDs in `route_ids`; downstream GTFS geometry remains one feature per route ID as required by the build specification.",
            "",
            "## Broken-reference details",
            "",
            f"- Missing route IDs referenced by trips: {missing_trip_routes or 'none'}",
            f"- Missing stop IDs referenced by stop_times: {missing_stop_refs or 'none'}",
            f"- Missing trip IDs referenced by frequencies: {missing_frequency_trips or 'none'}",
            "",
            "## Overall result",
            "",
            "PASS" if all(count == 0 for count in integrity.values()) else "FAIL - inspect details above",
        ]
    )
    (PROCESSED_DIR / "audit_report.md").write_text("\n".join(report) + "\n", encoding="utf-8")

    print("Route2Zero GTFS audit")
    for relationship, missing in integrity.items():
        print(f"[{'PASS' if missing == 0 else 'FAIL'}] {relationship}: {missing} missing")
    print(f"[PASS] wrote {PROCESSED_DIR / 'audit_report.md'}")
    return 0 if all(count == 0 for count in integrity.values()) else 1


if __name__ == "__main__":
    sys.exit(main())

