"""Task 12: generate one-page Markdown briefs for priority corridors."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

from bedrock_client import deterministic_route_rationale
from common import DOCS_DIR, PROCESSED_DIR, ensure_output_dirs


SPOTLIGHT_CITIES = ("Marikina", "Makati", "Malabon")


def value(value: object, suffix: str = "", digits: int = 1) -> str:
    return "Data not available" if pd.isna(value) else f"{float(value):.{digits}f}{suffix}"


def main() -> int:
    ensure_output_dirs()
    scores = pd.read_csv(PROCESSED_DIR / "route2zero_scores.csv", dtype={"route_id": str})
    cities = pd.read_csv(PROCESSED_DIR / "route_cities.csv", dtype={"route_id": str})
    scores = scores.merge(cities, on="route_id", how="left")
    scores = scores.dropna(subset=["just_transition_score"]).sort_values("rank")
    explanation_path = PROCESSED_DIR / "route_explanations.json"
    explanations = json.loads(explanation_path.read_text(encoding="utf-8")) if explanation_path.exists() else {}

    selected_ids = list(scores.head(5)["route_id"])
    for city in SPOTLIGHT_CITIES:
        candidates = scores[scores["cities_served"].fillna("").str.split("|").map(lambda values: city in values)]
        if not candidates.empty:
            selected_ids.append(candidates.iloc[0]["route_id"])
    selected_ids = list(dict.fromkeys(selected_ids))
    output_dir = DOCS_DIR / "policy_briefs"
    output_dir.mkdir(parents=True, exist_ok=True)

    for route_id in selected_ids:
        row = scores.loc[scores["route_id"].eq(route_id)].iloc[0]
        rationale = explanations.get(route_id, {}).get("text") or deterministic_route_rationale(row)
        narrative_source = explanations.get(route_id, {}).get("source", "deterministic_fallback")
        text = f"""# Route2Zero priority brief: {row['route_long_name']}

**Route ID:** `{row['route_id']}`  
**Default overall rank:** #{int(row['rank'])} of {scores['just_transition_score'].notna().sum():,} ranked routes  
**Cities served:** {row['cities_served'].replace('|', ', ')}  
**Just Transition Score:** {row['just_transition_score']:.1f}/100

## Why examine this corridor first

{rationale}

This narrative explains the deterministic score shown below; it does not influence the score or rank. Narrative source: `{narrative_source}`.

## Current service profile

| Indicator | Route value | Evidence status |
|---|---:|---|
| Approximate route length | {value(row['length_km'], ' km')} | Geodesic length along `{row['geometry_source']}` geometry |
| Representative stops | {int(row['stop_count'])} | GTFS ordered stop sequence |
| Average weekday headway | {value(row['avg_headway_min'], ' min')} | Historic GTFS frequencies |
| Estimated weekday trips | {value(row['trips_per_day_estimate'])} | Service window / average headway proxy |

## Score breakdown

| Dimension | Score | What the number means |
|---|---:|---|
| Emissions-reduction potential | {value(row['emissions_potential_score'], '/100')} | Relative route activity: length × estimated trips, not measured emissions |
| Equity | {value(row['equity_score'], '/100')} | High-density WorldPop exposure within 300 m, not informal-settlement boundaries |
| Grid feasibility | {value(row['grid_feasibility_score'], '/100')} | Shared 2024 Luzon renewable-generation share proxy |
| Operator readiness | {value(row['operator_readiness_score'], '/100')} | Neutral placeholder pending cooperative financing evidence |

Default weights are 40% climate impact, 30% equity, 15% charging readiness, and 15% operator readiness. Route ranking is a transparent weighted sum.

## Pilot decision and validation request

Invite the relevant LGU, LTFRB representatives, operators, and rider groups to validate the route geometry and service pattern; confirm depot/charging options; collect cooperative financing readiness; and review the equity proxy against locally known communities. The corridor should move from analytical shortlist to investment pipeline only after those checks.

## Confidence notes

- GTFS validity dates span 2013-2020 and must be refreshed during the pilot.
- Geometry source: `{row['geometry_source']}`.
- Equity source: `{row['equity_source']}` ({row['equity_confidence']}).
- Grid source: `{row['grid_source']}` ({row['grid_confidence']}).
- Operator source: `{row['operator_source']}`.

*Generated by Route2Zero on 14 August 2026. Re-run `python src/10_policy_brief.py` after data or score updates.*
"""
        (output_dir / f"{route_id}.md").write_text(text, encoding="utf-8")
    print(f"[PASS] policy briefs generated: {len(selected_ids)}")
    print(f"[PASS] wrote {output_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
